### ISSUE TITLE
图片返回 优化

### ISSUE THREAD

**Issue by vipheyue** [Werb/PickPhotoSample#1]
建议通过 listener 返回 不通过onActivityResult

**Comment by werbhelius** [comment]
选择图片和返回处理图片，属于Activity 场景之间的切换，使用 onActivityResult 是一种最常见通用的方式，我觉得 listener 一般是用于同一场景下的响应回调处理，我个人觉得还是onActivityResult合理一点，对于场景间的回调，我还没有尝试过 listener ，如果你有什么好的方法，可以贴出来学习一下～～

刚刚完成的库，有很多不成熟的地方，多多提出建议

Thanks
