### ISSUE TITLE
希望加添加已选中图片默认勾选的功能

### ISSUE THREAD

**Issue by Janky-Young** [Werb/PickPhotoSample#11]
当已经选择一些照片后，第二次再次进入图库进行选择时，希望第一次已经选择的图片是默认勾选的状态，希望加上这个功能，谢谢！

**Comment by werbhelius** [comment]
按功能逻辑来说，点击选择是一个一次性的行为，勾选图片后，有选取和返回，点击选取进行之后的业务逻辑，点击返回不应该保存之前选取图片的状态。这个取决于业务逻辑的性质，可以考虑，但优先级不高。

**Comment by Janky-Young** [comment]
点击选择只是选择了照片，如果点了确定之后需要修改选择的照片呢，类似论坛、朋友圈之类的，需要对选择的图片进行第二次修改。如果没有默认那不是要重新选么
