### ISSUE TITLE
HTC-e9pw 打不开相机

### ISSUE THREAD

**Issue by junge89221** [Werb/PickPhotoSample#17]
点击相册的相机按钮，打不开相机！不只是HTC，是所有的，是没有做这个功能？

**Comment by werbhelius** [comment]
相机可以啊，有log么？

**Comment by junge89221** [comment]
你有没有qq 我找到了原因，但是不知道怎么改，具体就是没有文件权限，你的demo也是报这个错误

**Comment by junge89221** [comment]
06-19 16:27:30.715 6884-6884/com.yishengyue.lifetime W/System.err: java.io.IOException: open failed: ENOENT (No such file or directory)
06-19 16:27:30.715 6884-6884/com.yishengyue.lifetime W/System.err:     at java.io.File.createNewFile(File.java:941)
06-19 16:27:30.716 6884-6884/com.yishengyue.lifetime W/System.err:     at com.werb.pickphotoview.adapter.PickGridAdapter$CameraViewHolder$1.onClick(PickGridAdapter.java:256)
06-19 16:27:30.716 6884-6884/com.yishengyue.lifetime W/System.err:     at android.view.View.performClick(View.java:4827)
06-19 16:27:30.716 6884-6884/com.yishengyue.lifetime W/System.err:     at android.view.View$PerformClick.run(View.java:20235)
06-19 16:27:30.716 6884-6884/com.yishengyue.lifetime W/System.err:     at android.os.Handler.handleCallback(Handler.java:810)
06-19 16:27:30.717 6884-6884/com.yishengyue.lifetime W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
06-19 16:27:30.717 6884-6884/com.yishengyue.lifetime W/System.err:     at android.os.Looper.loop(Looper.java:209)
06-19 16:27:30.717 6884-6884/com.yishengyue.lifetime W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5900)
06-19 16:27:30.717 6884-6884/com.yishengyue.lifetime W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
06-19 16:27:30.717 6884-6884/com.yishengyue.lifetime W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
06-19 16:27:30.717 6884-6884/com.yishengyue.lifetime W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1005)
06-19 16:27:30.717 6884-6884/com.yishengyue.lifetime W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:800)
06-19 16:27:30.717 6884-6884/com.yishengyue.lifetime W/System.err: Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
06-19 16:27:30.718 6884-6884/com.yishengyue.lifetime W/System.err:     at libcore.io.Posix.open(Native Method)
06-19 16:27:30.718 6884-6884/com.yishengyue.lifetime W/System.err:     at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
06-19 16:27:30.718 6884-6884/com.yishengyue.lifetime W/System.err:     at java.io.File.createNewFile(File.java:934)

**Comment by werbhelius** [comment]
wx 1025004680

**Comment by werbhelius** [comment]
Fixed

**Comment by highresfelix** [comment]
How did you fix it? @Werb
