### ISSUE TITLE
Image Viewer Orientation Incorrect

### ISSUE THREAD

**Issue by rayliverified** [Werb/PickPhotoSample#22]
When an image is clicked and the image viewer opens, no orientation is applied. This means images taken with the camera including rotation are not displayed correctly in the viewer. They are displayed correctly in the image picker however.

**Comment by rayliverified** [comment]
The source of the issue can be found at instantiateItem() in PickPhotoPreviewActivity on Line 134.
The LargeImageView library used does not support reading orientation. The only way to fix the problem would be to decode the bitmap with the correct orientation matrix and then pass it to LargeImageView which defeats the point of LargeImageView altogether. The other option is to edit LargeImageView with orientation support which is not ideal. 
I would suggest removing LargeImageView and just use ImageView with Glide. This would remove an additional dependency by the library. It is good for libraries to have as few dependencies as possible!

**Comment by rayliverified** [comment]
It is very easy to replace LargeImageView with Glide. If that works for you, I'll make a PR for it!

**Comment by werbhelius** [comment]
@searchy2  At the beginning LargeImageView is to solve the problem of the large image display

**Comment by rayliverified** [comment]
@Werb Thanks for merging the PR! This is a great library and I am happy to help make it even better :) 

This issue should not be closed just yet. The orientation issue is not yet fixed.

**Comment by werbhelius** [comment]
@searchy2 yeah, i will remove LargeImageView and just use glide to solve large image display and zoom attach, Glide is a good way to avoid OOM

**Comment by rayliverified** [comment]
Has this issue been solved? If not, I can paste my image orientation code here.

**Comment by werbhelius** [comment]
fixed in release [v0.3.5 ](https://github.com/Werb/PickPhotoSample/releases/tag/v0.3.5)
