### ISSUE TITLE
Selected Images Not Remember When Folders Switched

### ISSUE THREAD

**Issue by rayliverified** [Werb/PickPhotoSample#23]
Images that are selected in one folder are not remembered if the user switches folders. Currently, if the user selects 2 images in one folder and then switches folders, the user's first 2 selections are cleared. The correct behavior should be that selected images are remembered. The user should only be able to select 1 image after switching folders (assuming an image limit of 3).

**Comment by rayliverified** [comment]
Fixed in PR #21 
Selected images are now remembered even when folders changed.

**Comment by werbhelius** [comment]
Thank you ！ it's Amazing
