### ISSUE TITLE
Does not support fragment

### ISSUE THREAD

**Issue by songwensw** [Werb/PickPhotoSample#28]
PickPhotoView start user  fragment.startactivity 

      private void start() {
            Intent intent = new Intent();
            intent.setClass(activity, PickPhotoActivity.class);
            intent.putExtra(PickConfig.INTENT_PICK_DATA, pickData);
            if (fragment != null) {
                fragment.startActivityForResult(intent, PickConfig.PICK_PHOTO_DATA);
            } else {
                activity.startActivityForResult(intent, PickConfig.PICK_PHOTO_DATA);
            }
        }

**Comment by werbhelius** [comment]
@songwensw 
```java
new PickPhotoView.Builder(context)
        .setPickPhotoSize(9)   //select max size
        .setShowCamera(true)   //is show camera
        .setSpanCount(4)       //SpanCount
        .setLightStatusBar(true)  // custom theme
        .setStatusBarColor("#ffffff")   // custom statusBar
        .setToolbarColor("#ffffff")   // custom toolbar
        .setToolbarIconColor("#000000")   // custom toolbar icon
        .setSelectIconColor("#00C07F")  // custom select icon
        .start();
```

try to use this method
