### ISSUE TITLE
Update Glide to v4.1.1

### ISSUE THREAD

**Issue by rayliverified** [Werb/PickPhotoSample#31]
*Glide should be updated to use the latest stable version.

**Comment by werbhelius** [comment]
ok ！ i will override this project

**Comment by rayliverified** [comment]
Are you going to do it or shall I?

**Comment by rayliverified** [comment]
I'll do it lol

**Comment by rayliverified** [comment]
Please review PR #33, thanks!

**Comment by werbhelius** [comment]
@searchy2 I'm rewriting the project use Kotlin , Probably this weekend finished

**Comment by rayliverified** [comment]
@Werb What are the benefits of moving to Kotlin?

Can you create a new repository with the Kotlin version? I don't know Kotlin so I won't be able to contribute further to the library if you do.

**Comment by werbhelius** [comment]
fixed in release [v0.3.5 ](https://github.com/Werb/PickPhotoSample/releases/tag/v0.3.5)
