### ISSUE TITLE
When using Single Select how to get the pickphoto Uri ?

### ISSUE THREAD

**Issue by Edward7Zhang** [Werb/PickPhotoSample#32]
When I using Single Select option,i just wanna use ImageView to display the photo by Uri,how can i get the photo's Uri?
Thank you?
`public void onActivityResult(int requestCode, int resultCode, Intent data) {
	super.onActivityResult(requestCode, resultCode, data);
	if (resultCode == 0) {
		return;
	}
	if (data == null) {
		return;
	}
	if (requestCode == PickConfig.PICK_PHOTO_DATA) {
		ArrayList<String> selectPaths = (ArrayList<String>) data.getSerializableExtra(PickConfig.INTENT_IMG_LIST_SELECT);
		Uri uri = Uri.parse(selectPaths.get(0));
		Log.e("uri", uri.toString());
		ContentResolver cr = this.getActivity().getContentResolver();
		try {
			Bitmap bitmap = BitmapFactory.decodeStream(cr.openInputStream(uri));
			dealPics(bitmap);
		} catch (FileNotFoundException e) {
			Log.e("Exception", e.getMessage(), e);
		}
	}
}`

**Comment by werbhelius** [comment]
**get Uri**
```Java
Uri parse = Uri.parse("file://" + selectPaths.get(0));
// or
Uri parse = Uri.fromFile(new File(selectPaths.get(0)))
```

**imageview display**
```java
imageView.setImageURI(Uri.fromFile(new File(selectPaths.get(0))));
```

**if you want get a bitmap to display**
```java
imageView.setImageBitmap(BitmapFactory.decodeFile(selectPaths.get(0)));
```

That's all 😁
