### ISSUE TITLE
Didn't find class "kotlinx.android.extensions.LayoutContainer

### ISSUE THREAD

**Issue by onlycyndi** [Werb/PickPhotoSample#38]
as title problem

**Comment by werbhelius** [comment]
New Version 0.3.6+ build with Kotlin new feature `LayoutContainer` , so you must add this command in your **module build.gradle**
```gradle
apply plugin: 'kotlin-android-extensions'
```
and config this command in `android{}`
```gradle
androidExtensions {
    experimental = true
}
```
**when new feature published in kotlin release version it will built-in code and no need for config**
