### ISSUE TITLE
有时第一次打开选择所有图片界面为空白（手机中有图片的前提）

### ISSUE THREAD

**Issue by ououmu** [Werb/PickPhotoSample#42]
有时候调用 new PickPhotoView.Builder(...).start 选择图片时界面为空白，关闭后再打开图片就能显示，请问我应该怎么修改？并不是每次都能重现这个问题，代码中也只是简单调用了图片选择的方法。

**Comment by phoeson** [comment]
I have the same issue

**Comment by phoeson** [comment]
出现的几率还是挺高的

**Comment by werbhelius** [comment]
fixed
