### ISSUE TITLE
Camera take photo returns a file size 0

### ISSUE THREAD

**Issue by phoeson** [Werb/PickPhotoSample#45]
After I take a new photo, it gives me a photo file which size is 0.
This file is in the folder {packageNameSpace}/Photo/filename.jpg, the path returned onActivityResult like:
/storage/emulated/0/com.coostone.ht/Photo/IMG_20181103_105210.jpg

But the actual photo file is ok (in folder ../DCIM/Camera/filename.jpg)

**Comment by werbhelius** [comment]
sometimes onActivityResult return success but this photo did not save immediately
