### ISSUE TITLE
sdk为什么导入了跟EventBus冲突了

### ISSUE THREAD

**Issue by Janky-Young** [Werb/PickPhotoSample#9]
你好，如题
我导入pickphotoview后报eventbus的类找不到了，移除导包又可以了

**Comment by werbhelius** [comment]
@yangzhenqi  有log 么？ evenbus 的 依赖哪个？ 我这边试一下看看是什么问题

**Comment by Janky-Young** [comment]
@Werb `compile 'org.greenrobot:eventbus:3.0.0'`

**Comment by werbhelius** [comment]
我这边测试是没有问题的，找到原因了嚒？

**Comment by Janky-Young** [comment]
还没。。。

**Comment by Janky-Young** [comment]
用我的电脑可以跑，我同事的电脑就冲突了，好奇怪。。
